export const LOAD_ALL_USER_REQUEST = "LOAD_ALL_USER_REQUEST"
export const LOAD_ALL_USER_SUCCESS = "LOAD_ALL_USER_SUCCESS"
export const LOAD_ALL_USER_FAIL= "LOAD_ALL_USER_FAIL"
export const CLEAR_ERROR = "CLEAR_ERRORS"
